# Generated by Django 4.0 on 2021-12-18 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_alter_message_created_alter_message_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='paticipants',
            field=models.ManyToManyField(blank=True, related_name='paticipants', to=settings.AUTH_USER_MODEL),
        ),
    ]
